project_3_django/blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

project_3_django/blog/blogs/urls.py
"""Defines URL patterns for blogs.""" 

from django.urls import path
from . import views 

app_name = 'blogs' 

urlpatterns = [  
    # Home page 
    path('', views.index, name='index'),
    # Page shows all the blogposts
    path('blogposts/', views.blogposts, name='blogposts'),
    # Page for all posts of current user
    path('my_blogposts/', views.my_blogposts, name='myposts'),
    # Detailed info about each blogpost
    path('blogposts/<int:blogpost_id>/', views.blogpost, name='blogpost'),
    # Page for adding a new blogpost
    path('new_post/', views.new_post, name='new_post'),
    # Edit blogpost
    path('edit_post/<int:blogpost_id>/', views.edit_post, name='edit_post'),
    


]

project_3_django/blog/users/urls.py
"""Defines URL patterns for users""" 
from django.urls import path, include
from . import views 

app_name = 'users' 
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

project_3_django/blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
    """An entry where user can write on any topic."""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model.""" 
        return self.title

project_3_django/blog/users/models.py
from django.db import models

# Create your models here.

project_3_django/blog/blogs/forms.py
from django import forms
from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title','text']
        labels = {'text': '', 'title': 'Enter title'}

project_3_django/blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogPostForm

# Create your views here.
def index(request):
    """Home page for Blog."""
    return render(request, 'blogs/index.html')

def blogposts(request):
    """Show all blogposts on the page."""
    blogposts = BlogPost.objects.order_by('date_added')
    context = {'blogposts': blogposts}
    return render(request, 'blogs/blogposts.html', context)

def blogpost(request, blogpost_id):
    """Show one post on the page."""
    blogpost = BlogPost.objects.get(id=blogpost_id)
    print(request)
    user = request.user # TODO: Check if request contains field 'user'
    is_author = user == blogpost.author
    context = {'blogpost': blogpost, 'is_author': is_author}
    return render(request, 'blogs/blogpost.html', context)

@login_required
def new_post(request):
    """Add a new blogpost."""
    if request.method != 'POST':
        # if GET - create a blank form for new post.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('blogs:blogposts')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request,'blogs/new_post.html', context)

@login_required
def edit_post(request, blogpost_id):
    """Edit existing blogpost."""
    blogpost = BlogPost.objects.get(id=blogpost_id)
    user = request.user
    if blogpost.author != user:
        raise Http404

    if request.method != 'POST':
        # If GET, pre-fill form with the current post.
        form = BlogPostForm(instance=blogpost)
    else:
        # POST data submitted, process data.
        form = BlogPostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogpost', blogpost_id=blogpost.id)

    context = {'blogpost': blogpost, 'form': form} 
    return render(request,'blogs/edit_post.html', context)

@login_required
def my_blogposts(request):
    """Show all blogposts of current user."""
    user = request.user
    # TODO: try: blogposts = BlogPost.objects.get(author=user)
    blogposts = BlogPost.objects.filter(author=user).order_by('date_added')
    context = {'blogposts': blogposts}
    return render(request, 'blogs/blogposts.html', context)

project_3_django/blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            # When user log in, redirect to a view function index (homapage) in blogs
            return redirect('blogs:index')

    # Display blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

project_3_django/blog/blogs/templates/blogpost.html
{% extends "base.html" %}

{% block content %}
<h3>{{ blogpost.title }}</h3>
<p>{{ blogpost.date_added }}</p>
<p>{{ blogpost.text }}</p>
<p>
    <a href="{% url 'blogs:edit_post' blogpost.id %}">Edit post</a>
</p>

{% endblock content %}

project_3_django/blog/blogs/templates/blogposts.html
{% extends "base.html" %}

{% block content %}
<p>Blogposts</p>
    <ul>
        {% for blogpost in blogposts %}
            <li>
                <a href="{% url 'blogs:blogpost' blogpost.id %}">{{ blogpost }}</a> 
            </li>
        {% empty %}
            <li>No blogposts have been added yet.</li>
        {% endfor %}
    </ul>
<p>If you want to add new post: <a href="{% url 'blogs:new_post' %}">Add a new Blogpost</a></p>
{% endblock content %}

project_3_django/blog/blogs/templates/blogs/base.html
<p>
    <a href="{% url 'blogs:index' %}">Blog</a> –
    <a href="{% url 'blogs:blogposts' %}">All Blogposts</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'blogs:myposts' %}">My Blogposts</a>
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %} {% endblock content %}

project_3_django/blog/blogs/templates/blogs/blogpost.html
{% extends "blogs/base.html" %}

{% block content %}
    <h3>{{ blogpost.title }}</h3>
    <p>{{ blogpost.date_added }}</p>
    <p>{{ blogpost.text }}</p>
    {% if is_author %}
        <p>
            <a href="{% url 'blogs:edit_post' blogpost.id %}">Edit post</a>
        </p>
    {% endif %}
{% endblock content %}

project_3_django/blog/blogs/templates/blogs/blogposts.html
{% extends "blogs/base.html" %}

{% block content %}
<p>Blogposts</p>
    <ul>
        {% for blogpost in blogposts %}
            <li>
                <a href="{% url 'blogs:blogpost' blogpost.id %}">{{ blogpost }}</a> 
            </li>
        {% empty %}
            <li>No blogposts have been added yet.</li>
        {% endfor %}
    </ul>
<p>If you want to add new post: <a href="{% url 'blogs:new_post' %}">Add a new Blogpost</a></p>
{% endblock content %}

project_3_django/blog/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}
<h3>Edit Blogpost:</h3>
<form action="{% url 'blogs:edit_post' blogpost.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

project_3_django/blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Welcome to my Blog</p>
    <p>In my blog you can read stories from my life.</p>
    <img src="https://miro.medium.com/max/1000/1*A5XHLbhOdA5T7ZsSwQqR0A.jpeg"alt="Image">
{% endblock content %}

project_3_django/blog/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}
<h3>Add new Blogpost:</h3>
<form action="{% url 'blogs:new_post' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add post</button>
</form>

{% endblock content %}

project_3_django/blog/blogs/templates/edit_post.html
{% extends "base.html" %}

{% block content %}
<h3>Edit Blogpost:</h3>
<form action="{% url 'blogs:edit_post' blogpost.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

project_3_django/blog/blogs/templates/index.html
{% extends "base.html" %}

{% block content %}
    <p>Welcome to my Blog</p>
    <p>In my blog you can read stories from my life.</p>
    <img src="https://miro.medium.com/max/1000/1*A5XHLbhOdA5T7ZsSwQqR0A.jpeg"alt="Image">
{% endblock content %}

project_3_django/blog/blogs/templates/new_post.html
{% extends "base.html" %}

{% block content %}
<h3>Add new Blogpost:</h3>
<form action="{% url 'blogs:new_post' %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add post</button>
</form>

{% endblock content %}