project_3_django/meal_planner/meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meal_plans.urls')),
]

project_3_django/meal_planner/meal_plans/urls.py
from django.urls import path
from . import views 

app_name = 'meal_plans' 
urlpatterns = [ 
    # Home page 
    path('', views.index, name='index'), 
    path('meals_posts/', views.meals_posts, name='meals_posts'),
    path('meals_posts/<int:meal_post_id>/',views.meal_post, name='meal_post'),

]

project_3_django/meal_planner/meal_plans/models.py
from django.db import models

# Create your models here.

class MealPost(models.Model):
    name = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model.""" 
        return self.name

project_3_django/meal_planner/meal_plans/views.py
from django.shortcuts import render, redirect
from .models import MealPost

# Create your views here.
def index(request):
    """The home page for Meal Planner."""
    return render(request, 'index.html')

def meals_posts(request):
    """Show all meal posts."""
    meals_posts = MealPost.objects.order_by('date_added')
    context = {'meals_posts': meals_posts}
    return render(request, 'meals_posts.html', context)

def meal_post(request, meal_post_id):
    """Show current meal post."""
    meal_post =MealPost.objects.get(id=meal_post_id)
    context = {'meal_post': meal_post}
    return render(request, 'meal_post.html', context)

project_3_django/meal_planner/meal_plans/templates/base.html
<p>
    <a href="{% url 'meal_plans:index' %}">Meal Planner</a> -
    <a href="{% url 'meal_plans:meals_posts' %}">Meal Posts</a>
</p>

{% block content %}

{% endblock content %}

project_3_django/meal_planner/meal_plans/templates/index.html
{% extends "base.html" %}

{% block content %}
<h3>Meal Planner</h3>
<body>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTOP_DHAQCipb1vYqksusIVeJ9qBD3HhZ1usw&usqp=CAU" alt="Food">

    <p>Meal Planner helps you with ideas for lunch or dinner and keep track of your calories.</p> 
</body>
{% endblock content %}

project_3_django/meal_planner/meal_plans/templates/meal_post.html
{% extends "base.html" %}

{% block content %}
    <h3>mealpost.name</h3>
    
    <p>{{ mealpost.text }}</p>
{% endblock content %}

project_3_django/meal_planner/meal_plans/templates/meals_posts.html
{% extends "base.html" %}

{% block content %}
<h3>Meal plans</h3>
<ul>
    {% for meal_post in meals_posts %}
    <li>
        <a href="{% url 'meal_plans:meal_post' meal_post.id %}">{{ meal_post }}</a>
    </li>
    {% empty %}
        <li>No meal plans have been added yet.</li>
    {% endfor %}
</ul>
{% endblock content %}