project_3_django/pizzeria/pizzas/urls.py
"""Defines URL patterns for pizzas."""
from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all avaliable pizzas.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Detailed page that shows chosen pizza's toppings.
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    # Page with all availablle toppings.
    path('toppings/', views.toppings, name='toppings'),

]

project_3_django/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    
]

project_3_django/pizzeria/pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        """Return a string representation of the model.""" 
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        """Return a string representation of the model.""" 
        return self.name

project_3_django/pizzeria/pizzas/views.py
from django.shortcuts import render
from .models import Pizza, Topping 

# Create your views here.
def index(request):
    """The home page for Pizzas."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizzas from database."""
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas': pizzas}
    # Building page with data, pass request object and the path to the template and pass the context variable to render().
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show toppings for current pizza."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    context = {'pizza':pizza, 'toppings':toppings}
    return render(request, 'pizzas/pizza.html', context)

def toppings(request):
    """Show all available toppings."""
    toppings = Topping.objects.all()
    context = {'toppings':toppings}
    return render(request, 'pizzas/toppings.html', context)

project_3_django/pizzeria/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a> –
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a> –
    <a href="{% url 'pizzas:toppings' %}">Toppings</a>


</p>

{% block content %}{% endblock content %}

project_3_django/pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
    <h2>Welcome to Veronica's pizzeria</h2>
    <body>
        <img src="https://img.cpcdn.com/recipes/1898301/640x480c0_144_320_240_320/010d4b7bbce52c85a55605ba20a57827.jpg?u=507858&p=1432992911" alt="Pizza">
    </body>
{% endblock content %}

project_3_django/pizzeria/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>
    {{ pizza }}
  </p>
  <ul>
    {% for topping in toppings %}
    <li>
      {{ topping }}
    </li>
    {% empty %}
      <li> 
        No toppings have been added yet.
      </li>
    {% endfor %}
  </ul>


{% endblock content %}

project_3_django/pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Our Pizzas</p>
<!-- bulleted list is called an unordered list (ul) -->
  <ul>
    <!-- loops through the list from the context dict -->
    {% for pizza in pizzas %}
      <li>
          <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
      <!--if there are no items in the list, using tag empty-->
    {% empty %}
      <li>No pizzas have been added yet.</li>
    {% endfor %}
  </ul>

{% endblock content %}

project_3_django/pizzeria/pizzas/templates/pizzas/toppings.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>Our avaliable toppings</p>
    <ul>
        {% for topping in toppings %}
        <li>
          {{ topping }}
        </li>
        {% empty %}
          <li> 
            No toppings have been added yet.
          </li>
        {% endfor %}
    </ul>
    
{% endblock content %}